# Generated by Django 3.0.2 on 2020-05-17 13:28

import ckeditor_uploader.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
	initial = True

	dependencies = [
	]

	operations = [
		migrations.CreateModel(
			name='NoteType',
			fields=[
				('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
				('section', models.CharField(max_length=10)),
			],
		),
		migrations.CreateModel(
			name='User',
			fields=[
				('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
				('name', models.CharField(max_length=128, unique=True)),
				('password', models.CharField(max_length=16)),
				('c_time', models.DateTimeField(auto_now_add=True)),
			],
			options={
				'verbose_name': '用户',
				'verbose_name_plural': '用户',
				'ordering': ['c_time'],
			},
		),
		migrations.CreateModel(
			name='Note',
			fields=[
				('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
				('title', models.CharField(max_length=50)),
				('time', models.DateField()),
				('content', ckeditor_uploader.fields.RichTextUploadingField()),
				('annex', models.FileField(upload_to='static/files/')),
				('author', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='part01.User')),
				('note_section',
				 models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='part01.NoteType')),
			],
			options={
				'ordering': ['-time'],
			},
		),
	]
