# Generated by Django 3.0.2 on 2020-05-17 13:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
	dependencies = [
		('part01', '0001_initial'),
	]

	operations = [
		migrations.RenameModel(
			old_name='NoteType',
			new_name='Section',
		),
		migrations.RemoveField(
			model_name='note',
			name='note_section',
		),
		migrations.AddField(
			model_name='user',
			name='section',
			field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='part01.Section'),
			preserve_default=False,
		),
	]
